## Numpy array and basics

In [22]:
import numpy as np
import time


### Creating array from list

In [16]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:\n", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr_2d)


1D array:
 [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [25]:
py_list = [1, 2, 3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3])
print("Python array multiplication: ", np_array * 2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.21286797523498535

 Numpy operation time:  0.011669397354125977


### Creating array from scratch

In [30]:
zeros = np.zeros((3, 4))
print("\n Zeros array:\n", zeros)

ones = np.ones((3, 4))
print("\n Ones array:\n", ones)

full = np.full((3, 4), 5)
print("\n Full array:\n", full)

arange = np.arange(1, 10, 2)
print("\n Arange array:\n", arange)

random = np.random.random((2, 3))
print("\n Random array:\n", random)



 Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 Full array:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

 Arange array:
 [1 3 5 7 9]

 Random array:
 [[0.42974104 0.7962005  0.43002931]
 [0.66921618 0.91741733 0.55060257]]


### Vector, Matrix, Tensor

In [32]:
vector = np.array([1, 2, 3])
print("\n Vector:\n", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("\n Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("\n Tensor:\n", tensor)



 Vector:
 [1 2 3]

 Matrix:
 [[1 2 3]
 [4 5 6]]

 Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
