## Numpy Array Operations

In [40]:
import numpy as np

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:8])
print("With Step:", arr[1:8:2])
print("Negative Indexing:", arr[-3:])

Basic Slicing: [3 4 5 6 7 8]
With Step: [2 4 6 8]
Negative Indexing: [ 8  9 10]


In [42]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])
print("Specific Element:", arr[1, 2]) # first row then column
print("Entire Row:", arr[1, :])
print("Entire Column:", arr[:, 1])


Specific Element: 6
Entire Row: [4 5 6]
Entire Column: [2 5 8]


## Sorting

In [43]:
unsorted = np.array([2, 1, 5, 3, 4, 7, 6])
print("Unsorted:", unsorted)
print("Sorted:", np.sort(unsorted))

arr_2d_unsorted = np.array([[2, 1], [5, 3], [2, 3], [4, 7], [6, 5]])
print("Unsorted 2D:", arr_2d_unsorted)
print("Sorted 2D by Column:", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D by Row:", np.sort(arr_2d_unsorted, axis=1))


Unsorted: [2 1 5 3 4 7 6]
Sorted: [1 2 3 4 5 6 7]
Unsorted 2D: [[2 1]
 [5 3]
 [2 3]
 [4 7]
 [6 5]]
Sorted 2D by Column: [[2 1]
 [2 3]
 [4 3]
 [5 5]
 [6 7]]
Sorted 2D by Row: [[1 2]
 [3 5]
 [2 3]
 [4 7]
 [5 6]]


## Filter

In [44]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numberss:", even_numbers)

arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
even_numbers_2d = arr_2d[arr_2d % 2 == 0]
print("Even numberss 2D:", even_numbers_2d)

Even numberss: [ 2  4  6  8 10]
Even numberss 2D: [ 2  4  6  8 10]


## Filter with mask

In [45]:
mask = numbers > 5
print("Mask:", mask)
print("Filtered numberss:", numbers[mask])


Mask: [False False False False False  True  True  True  True  True]
Filtered numberss: [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [46]:
indices = [0, 2, 4, 6, 8]
print(numbers[indices])

where_result = np.where(numbers < 5)
print(where_result)
print(numbers[where_result])

[1 3 5 7 9]
(array([0, 1, 2, 3]),)
[1 2 3 4]


In [47]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)
# --- Working ---
# if(numbers > 5):
#     numbers*2
# else:
#     numbers
# ---------------

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and Removing Data

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined:", combined)

Combined: [1 2 3 4 5 6]


## Array Compatibility

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 10])

print("Compatibility shapes a and b:", a.shape == b.shape)
print("Compatibility shapes b and c:", b.shape == c.shape)


Compatibility shapes a and b: True
Compatibility shapes b and c: False


In [50]:
original = np.array([[1, 2, 3], 
                    [4, 5, 6]])
print("Original array:", original)
new_row = np.array([7, 8, 9])

with_new_row = np.vstack((original, new_row))
print("Array with new row:", with_new_row)

new_column = np.array([[10], [11]])
with_new_column = np.hstack((original, new_column))
print("Array with new column:", with_new_column)


Original array: [[1 2 3]
 [4 5 6]]
Array with new row: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with new column: [[ 1  2  3 10]
 [ 4  5  6 11]]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

deleted = np.delete(arr, 2)
print("Original array after deletion:", arr)
print("'deleted' variable stores:", deleted) # same


Original array: [1 2 3 4 5 6 7 8 9]
Original array after deletion: [1 2 3 4 5 6 7 8 9]
'deleted' variable stores: [1 2 4 5 6 7 8 9]
