## Numpy Array Operations

In [78]:
import numpy as np

In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:8])
print("With Step:", arr[1:8:2])
print("Negative Indexing:", arr[-3:])

Basic Slicing: [3 4 5 6 7 8]
With Step: [2 4 6 8]
Negative Indexing: [ 8  9 10]


In [80]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])
print("Specific Element:", arr[1, 2]) # first row then column
print("Entire Row:", arr[1, :])
print("Entire Column:", arr[:, 1])


Specific Element: 6
Entire Row: [4 5 6]
Entire Column: [2 5 8]


## Sorting

In [81]:
unsorted = np.array([2, 1, 5, 3, 4, 7, 6])
print("Unsorted:", unsorted)
print("Sorted:", np.sort(unsorted))

arr_2d_unsorted = np.array([[2, 1], [5, 3], [2, 3], [4, 7], [6, 5]])
print("Unsorted 2D:", arr_2d_unsorted)
print("Sorted 2D by Column:", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D by Row:", np.sort(arr_2d_unsorted, axis=1))


Unsorted: [2 1 5 3 4 7 6]
Sorted: [1 2 3 4 5 6 7]
Unsorted 2D: [[2 1]
 [5 3]
 [2 3]
 [4 7]
 [6 5]]
Sorted 2D by Column: [[2 1]
 [2 3]
 [4 3]
 [5 5]
 [6 7]]
Sorted 2D by Row: [[1 2]
 [3 5]
 [2 3]
 [4 7]
 [5 6]]


## Filter

In [82]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numberss:", even_numbers)

arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
even_numbers_2d = arr_2d[arr_2d % 2 == 0]
print("Even numberss 2D:", even_numbers_2d)

Even numberss: [ 2  4  6  8 10]
Even numberss 2D: [ 2  4  6  8 10]


## Filter with mask

In [83]:
mask = numbers > 5
print("Mask:", mask)
print("Filtered numberss:", numbers[mask])


Mask: [False False False False False  True  True  True  True  True]
Filtered numberss: [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [84]:
indices = [0, 2, 4, 6, 8]
print(numbers[indices])

where_result = np.where(numbers < 5)
print(where_result)
print(numbers[where_result])

[1 3 5 7 9]
(array([0, 1, 2, 3]),)
[1 2 3 4]


In [85]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)
# --- Working ---
# if(numbers > 5):
#     numbers*2
# else:
#     numbers
# ---------------

[ 1  2  3  4  5 12 14 16 18 20]
